DELETE FROM "Games";


INSERT INTO "Games"
    ("GameId", "GameStarted", "PublicGame", "IconImage", "NumberOfQuestions", "CreatorId", "Upvotes")
VALUES
    ('KICKSTARTER', true, true, 'EDGY', 129, 'Creator', 32);

INSERT INTO "Questions"
    ("GameId", "QuestionStr")
VALUES
    ('KICKSTARTER', 'Hvem er morsomst?'),
    ('KICKSTARTER', 'Hvem tror selv den er morsomst?'),
    ('KICKSTARTER', 'Hvem har størst kjendisfaktor?'),
    ('KICKSTARTER', 'Hvem har søtest familie?'),
    ('KICKSTARTER', 'Hvem har hatt sex med flest yngre?'),
    ('KICKSTARTER', 'Hvem kunne hatt sex med flest i klassen?'),
    ('KICKSTARTER', 'Hvem er mest opptatt av utsjånaden?'),
    ('KICKSTARTER', 'Hvem er mest fornøyd med eiga utsjånad?'),
    ('KICKSTARTER', 'Hvem komme raskast?'),
    ('KICKSTARTER', 'Hvem har minst penis?'),
    ('KICKSTARTER', 'Hvem er størst i kjeften?'),
    ('KICKSTARTER', 'Hvem er mest overlegen?'),
    ('KICKSTARTER', 'Hvem er mest sporty?'),
    ('KICKSTARTER', 'Hvem har hatt sex med flest?'),
    ('KICKSTARTER', 'Hvem har hatt flest orgasmar?'),
    ('KICKSTARTER', 'Hvem er mest vill?'),
    ('KICKSTARTER', 'Hvem har best kropp?'),
    ('KICKSTARTER', 'Hvem er mest spontan?'),
    ('KICKSTARTER', 'Hvem er mest uskyldige?'),
    ('KICKSTARTER', 'Hvem laga dei sjukaste lydene i senga?'),
    ('KICKSTARTER', 'Hvem ler mest i timen?'),
    ('KICKSTARTER', 'Hvem har finast antrekk?'),
    ('KICKSTARTER', 'Hvem smisker mest med læreren?'),
    ('KICKSTARTER', 'Hvem har mest spennende rumpe?'),
    ('KICKSTARTER', 'Hvem kunne prostituert seg?'),
    ('KICKSTARTER', 'Hvem stirrer mest i timene?'),
    ('KICKSTARTER', 'Hvem er den mest voldelige jenta?'),
    ('KICKSTARTER', 'Hvem spiser mest?'),
    ('KICKSTARTER', 'Hvem har diggest pupper?'),
    ('KICKSTARTER', 'Hvem vil du danse med i kveld?'),
    ('KICKSTARTER', 'Hvilken jente er mest bro?'),
    ('KICKSTARTER', 'Hvilken gutt får du vakrast barn saman med?'),
    ('KICKSTARTER', 'Hvem har du et lite mye til?'),
    ('KICKSTARTER', 'Hvem har shava og er forberedt på alt?'),
    ('KICKSTARTER', 'Hvem hadde vært den beste telefonselgeren?'),
    ('KICKSTARTER', 'Hvem er den største fylliken?'),
    ('KICKSTARTER', 'Hvilken gutt får du vakrest barn med?'),
    ('KICKSTARTER', 'Hvem er den beste til å kysse?'),
    ('KICKSTARTER', 'Hvem ler mest i timen?'),
    ('KICKSTARTER', 'Har lyst å komme i buksa på i kveld?'),
    ('KICKSTARTER', 'Hvem blir raskast sjalu?'),
    ('KICKSTARTER', 'Hvem ligner mest på en taco?'),
    ('KICKSTARTER', 'Hvem har hatt sex med flest eldre?'),
    ('KICKSTARTER', 'Hvem har hatt trekant?'),
    ('KICKSTARTER', 'Hvem har hatt sex med flest årskull?'),
    ('KICKSTARTER', 'Hvem er mest flørtete?'),
    ('KICKSTARTER', 'Hvem er hyggeligst?'),
    ('KICKSTARTER', 'Hvem snakker mest engelsk?'),
    ('KICKSTARTER', 'Hvem er mest desperat etter å miste jomfrudommen?'),
    ('KICKSTARTER', 'Hvem er den vakreste i rommet?'),
    ('KICKSTARTER', 'Hvem stoler du mest på?'),
    ('KICKSTARTER', 'Hvem tar med seg nåken heim i kveld?'),
    ('KICKSTARTER', 'Hvem får kjæreste i år?'),
    ('KICKSTARTER', 'Hvem blir gravid først?'),
    ('KICKSTARTER', 'Hvem spyr i kveld?'),
    ('KICKSTARTER', 'Hvem slutta på studiet?'),
    ('KICKSTARTER', 'Hvem blir mest drita i kveld?'),
    ('KICKSTARTER', 'Hvem blir pappa først?'),
    ('KICKSTARTER', 'Hvem gifta seg først?'),
    ('KICKSTARTER', 'Hvem har finast lepper?'),
    ('KICKSTARTER', 'Hvem burde vært elevråd?'),
    ('KICKSTARTER', 'Hvem burde ikke vært elevråd?'),
    ('KICKSTARTER', 'Hvem er minst?'),
    ('KICKSTARTER', 'Hvem er mest langsint?'),
    ('KICKSTARTER', 'Hvem mest sannsynlig til å prøve anal?'),
    ('KICKSTARTER', 'Hvem mest sannsynlig lebisk/homofil?'),
    ('KICKSTARTER', 'Hvem kunne hatt sex me samme kjønn, uten å være homofil?'),
    ('KICKSTARTER', 'Hvem er tøffest?'),
    ('KICKSTARTER', 'Hvem lyser opp rommet?'),
    ('KICKSTARTER', 'Hvem har runka mest?'),
    ('KICKSTARTER', 'Hvem tar seg mest på brysta?'),
    ('KICKSTARTER', 'Hvem ser mest på porno?'),
    ('KICKSTARTER', 'Hvem finger mest?'),
    ('KICKSTARTER', 'Hvem drikker raskast?'),
    ('KICKSTARTER', 'Hvem gifter seg for penger?'),
    ('KICKSTARTER', 'Hvem tar plastisk operasjon?'),
    ('KICKSTARTER', 'Hvem tar farligst forbikjøringer?'),
    ('KICKSTARTER', 'Hvem hat gjort mest for å vinne et veddemål?'),
    ('KICKSTARTER', 'Hvem ender opp som kriminell?'),
    ('KICKSTARTER', 'Hvem har blitt pumpa?'),
    ('KICKSTARTER', 'Hvem er den beste sjåføren?'),
    ('KICKSTARTER', 'Hvem handler mest på salg?'),
    ('KICKSTARTER', 'Hvem er jomfru lengst?'),
    ('KICKSTARTER', 'Hvem ville du vært på en øde øy med?'),
    ('KICKSTARTER', 'Hvem er det største talentet?'),
    ('KICKSTARTER', 'Hvem er minst flink til å bruke prevensjon?'),
    ('KICKSTARTER', 'Hvem slutter på studiet'),
    ('KICKSTARTER', 'Hvem har mest kinky sex?'),
    ('KICKSTARTER', 'Hvem har en kjønnssykdom akkurat nå?'),
    ('KICKSTARTER', 'Hvem har hatt flest orgasmer?'),
    ('KICKSTARTER', 'Hvem sprer mest rykter?'),
    ('KICKSTARTER', 'Hvem er dagens 0?'),
    ('KICKSTARTER', 'Hvem er gravid akkurat nå?'),
    ('KICKSTARTER', 'Hvem har shavet og er forberedt på alt?'),
    ('KICKSTARTER', 'Hvem har klippekort på abortklinikken?'),
    ('KICKSTARTER', 'Hvem er mest sannsynlig til å ha trekant med tvillinger?'),
    ('KICKSTARTER', 'Hvem er mest ubesluttsom?'),
    ('KICKSTARTER', 'Hvem er en golddigger?'),
    ('KICKSTARTER', 'Hvem har du lyst å komme i buksa på i kveld?'),
    ('KICKSTARTER', 'Hvem er mest kåt?'),
    ('KICKSTARTER', 'Hvem får du vakrest barn med?'),
    ('KICKSTARTER', 'Hvem er mest hang imorgen?'),
    ('KICKSTARTER', 'Hvem har blitt pumpa?'),
    ('KICKSTARTER', 'Hvem bruker mest tid på å shave pikken/fitta?'),
    ('KICKSTARTER', 'Hvem er mest fuckboy?'),
    ('KICKSTARTER', 'Hvem lager de sykeste lydene i senga?'),
    ('KICKSTARTER', 'Hvem er mest luremus?'),
    ('KICKSTARTER', 'Hvem har de sykeste fetishene?'),
    ('KICKSTARTER', 'Hvem er mest fornøyd med eget utseende?'),
    ('KICKSTARTER', 'Hvem ser mest på porno?'),
    ('KICKSTARTER', 'Hvem fingrer mest?'),
    ('KICKSTARTER', 'Hvem spyr ikveld?'),
    ('KICKSTARTER', 'Hvem havner på rommet til hosten med noen ikveld?'),
    ('KICKSTARTER', 'Hvem er mest sjalu?'),
    ('KICKSTARTER', 'Hvem tar mest drugs?'),
    ('KICKSTARTER', 'Hvem har spenstige tits?'),
    ('KICKSTARTER', 'Hvem snakker minst?'),
    ('KICKSTARTER', 'Hvem gir mest til veldedighet?'),
    ('KICKSTARTER', 'Hvem spurter den mest massive cumshoten?'),
    ('KICKSTARTER', 'Hvem får klamma i øyet av den mest massive cumshoten?'),
    ('KICKSTARTER', 'Hvem dauver av kreft?'),
    ('KICKSTARTER', 'Hvem hadde sex sist?'),
    ('KICKSTARTER', 'Hvem runker mest?'),
    ('KICKSTARTER', 'Hvem har thiccest ass?'),
    ('KICKSTARTER', 'Hvem kommer raskest?'),
    ('KICKSTARTER', 'Hvem kom i puberteten sist?'),
    ('KICKSTARTER', 'Hvem har størst pikk?'),
    ('KICKSTARTER', 'Hvem driver mest blasfemi?'),
    ('KICKSTARTER', 'Hvem blir forelder først?'),
    ('KICKSTARTER', 'Hvem vinner Farmen?'),
    ('KICKSTARTER', 'Hvem kramper neste år?'),
    ('KICKSTARTER', 'Hvem har du et godt øye til?'),
    ('KICKSTARTER', 'Hvem har hatt det vanskeligste livet?'),
    ('KICKSTARTER', 'Hvem er mest lilla?'),
    ('KICKSTARTER', 'Hvem er mest desp?'),
    ('KICKSTARTER', 'Hvem griner mest?'),
    ('KICKSTARTER', 'Hvem blir sendt ut av Ex on The Beach av Padden?'),
    ('KICKSTARTER', 'Hvem er dårligst på å holde hemmeligheter?'),
    ('KICKSTARTER', 'Hvem er hyggeligere enn de ser ut som?'),
    ('KICKSTARTER', 'Hvem er den største nevemagneten?'),
    ('KICKSTARTER', 'Hvem er største snaphora?'),
    ('KICKSTARTER', 'Hvem klår mest?'),
    ('KICKSTARTER', 'Hvem bryr seg minst om hvem de hooker med?'),
    ('KICKSTARTER', 'Hvem mista jomfrudommen først?'),
    ('KICKSTARTER', 'Hvem vil du se naken?'),
    ('KICKSTARTER', 'Hvem tar seg mest på puppene sine?'),
    ('KICKSTARTER', 'Hvem har flest psykiske lidelser?'),
    ('KICKSTARTER', 'Hvem skaper mest drama i hotellet?'),
    ('KICKSTARTER', 'Hvem savner RT mest?'),
    ('KICKSTARTER', 'Hvem investerer mest aksjer?'),
    ('KICKSTARTER', 'Hvem dauver av overdose?'),
    ('KICKSTARTER', 'Hvem har dårligst humor?'),
    ('KICKSTARTER', 'Hvem ødelegger mest?'),
    ('KICKSTARTER', 'Hvem er mest sannsynlig til å spille inn porno film?'),
    ('KICKSTARTER', 'Hvem hadde banga broren/søsteren sin?'),
    ('KICKSTARTER', 'Hvem er mest dramaqueen?'),
    ('KICKSTARTER', 'Hvem har mange soveplasser?'),
    ('KICKSTARTER', 'Hvem gifter seg med en som har gått på BI?');


INSERT INTO "Games"
    ("GameId", "GameStarted", "PublicGame", "IconImage", "NumberOfQuestions", "CreatorId", "Upvotes")
VALUES
    ('LETT VORS', true, true, 'DIRTY', 60, 'Creator', 25);

INSERT INTO "Questions"
    ("GameId", "QuestionStr")
VALUES
    ('LETT VORS', 'Hvem lager de gøyeste vorsene?'),
    ('LETT VORS', 'Hvem bruker mest penger på byen?'),
    ('LETT VORS', 'Hvem har finest kjønnsorgan?'),
    ('LETT VORS', 'Hvem er mest harry?'),
    ('LETT VORS', 'Hvem er mest dirty?'),
    ('LETT VORS', 'Hvem har sykeste fetishen?'),
    ('LETT VORS', 'Hvem gir snusboksen videre med et kyss?'),
    ('LETT VORS', 'Hvem er alltid med på fylla?'),
    ('LETT VORS', 'Hvem kjører mest brannbil?'),
    ('LETT VORS', 'Hvem er mest luremus?'),
    ('LETT VORS', 'Hvem mistet jomfrudommen først?'),
    ('LETT VORS', 'Hvem mistet jomfrudommen sist?'),
    ('LETT VORS', 'Hvem har flest sexleketøy?'),
    ('LETT VORS', 'Hvem kunne kjøpt sex?'),
    ('LETT VORS', 'Hvem har mest sexy antrekk?'),
    ('LETT VORS', 'Hvem gir best rimjob?'),
    ('LETT VORS', 'Hvem sender flest nudes?'),
    ('LETT VORS', 'Hvem mottar flest nudes?'),
    ('LETT VORS', 'Hvem har en dilf/milf?'),
    ('LETT VORS', 'Hvem har sexet flest fra Tinder?'),
    ('LETT VORS', 'Hvem svelger alltid?'),
    ('LETT VORS', 'Hvem kommer flest ganger i løpet av en økt?'),
    ('LETT VORS', 'Hvem har flest ONS?'),
    ('LETT VORS', 'Hvem har sugd en hund for 100.000 kr?'),
    ('LETT VORS', 'Hvem blir ferdig på 2 minutter?'),
    ('LETT VORS', 'Hvem svetter mest under sex?'),
    ('LETT VORS', 'Hvem har hatt sex med flest?'),
    ('LETT VORS', 'Hvem er festens sugeguri?'),
    ('LETT VORS', 'Hvem er festens slikkerolf?'),
    ('LETT VORS', 'Hvem vil du komme i buksa på i kveld?'),
    ('LETT VORS', 'Hvem sovner under sex?'),
    ('LETT VORS', 'Hvem liker BDSM?'),
    ('LETT VORS', 'Hvem er mest kreativ i loppekassa?'),
    ('LETT VORS', 'Hvem jobber mest på byen?'),
    ('LETT VORS', 'Hvem er best å ha sex med i rommet?'),
    ('LETT VORS', 'Hvem får mest oppmerksomhet på byen?'),
    ('LETT VORS', 'Hvem får oftest whiskydick?'),
    ('LETT VORS', 'Hvem blir mest ulik seg selv på fylla?'),
    ('LETT VORS', 'Hvem chugger raskest?'),
    ('LETT VORS', 'Hvem blir mest rejecta på byen?'),
    ('LETT VORS', 'Hvem shotter mest?'),
    ('LETT VORS', 'Hvem er beste wingman/woman?'),
    ('LETT VORS', 'Hvem er villest på vors?'),
    ('LETT VORS', 'Hvem barberer seg sjeldnest?'),
    ('LETT VORS', 'Hvem er vorsets kamasutra?'),
    ('LETT VORS', 'Hvem har onanert før vors?'),
    ('LETT VORS', 'Hvem har sugd den mest massive black anaconda''en?'),
    ('LETT VORS', 'Hvem går alltid tilbake til exen?'),
    ('LETT VORS', 'Hvem er kåtest i rommet?'),
    ('LETT VORS', 'Hvem kunne meldt seg på Ex on the Beach?'),
    ('LETT VORS', 'Hvem er lettest på tråden?'),
    ('LETT VORS', 'Hvem deler sexlivet sitt med alle?'),
    ('LETT VORS', 'Hvem faker flest orgasmer?'),
    ('LETT VORS', 'Hvem er høylytt i sengen?'),
    ('LETT VORS', 'Hvem får oftest fylleangst?'),
    ('LETT VORS', 'Hvem er den største goldiggeren?'),
    ('LETT VORS', 'Hvem er den største cougaren?'),
    ('LETT VORS', 'Hvem ville sexet faren/moren til en venn?'),
    ('LETT VORS', 'Hvem kunne solgt brukte truser på nett?'),
    ('LETT VORS', 'Hvem shopper flest angrepiller?'),
    ('LETT VORS', 'Hvem er oftest å se på helsestasjonen?'),
    ('LETT VORS', 'Hvem loker mest rundt på Pornhub?'),
    ('LETT VORS', 'Hvem bruker buttpluggen flittigst?'),
    ('LETT VORS', 'Hvem er minst kresen?'),
    ('LETT VORS', 'Hvem ble utestengt under en trekant?');    


INSERT INTO "Games"
    ("GameId", "GameStarted", "PublicGame", "IconImage", "NumberOfQuestions", "CreatorId", "Upvotes")
VALUES
    ('ICEBREAKER', true, true, 'EDGY', 42, 'Creator', 20);


INSERT INTO "Questions"
    ("GameId", "QuestionStr")
VALUES
    ('ICEBREAKER', 'Alle tar en skål for VOOOORS?'),
    ('ICEBREAKER', 'Den laveste begynner?'),
    ('ICEBREAKER', 'Hvem er den høyeste du har pult?'),
    ('ICEBREAKER', 'Hva er din favoritt sex stilling?'),
    ('ICEBREAKER', 'Hva er din verste sex historie?'),
    ('ICEBREAKER', 'Bit den til høyre i øret på en sexy måte?'),
    ('ICEBREAKER', 'Lag en stønnelyd du tror partneren din ville likt i sengen?'),
    ('ICEBREAKER', 'Jeg har aldri crushet på en i rommet?'),
    ('ICEBREAKER', 'Jeg har aldri sett på Gay porn?'),
    ('ICEBREAKER', 'Jeg har aldri blitt fersket i å runke eller fingre?'),
    ('ICEBREAKER', 'Jeg har aldri vært polesister med en god venn?'),
    ('ICEBREAKER', 'Jeg har aldri rotet med mer enn 1 person på en kveld?'),
    ('ICEBREAKER', 'Jeg har aldri hatt sex med noen mer enn 5 år eldre enn meg selv?'),
    ('ICEBREAKER', 'Jeg har aldri hatt planer om å hooke med noen i dette rommet i kveld?'),
    ('ICEBREAKER', 'Jeg har aldri vært utro?'),
    ('ICEBREAKER', 'Jeg har aldri blitt kåt av paradise hotel?'),
    ('ICEBREAKER', 'Jeg har aldri tatt noen sin jomfrudom?'),
    ('ICEBREAKER', 'Pek på den du tror er mest fornøyd med eget utseende?'),
    ('ICEBREAKER', 'Pek på den du tror er best i sengen?'),
    ('ICEBREAKER', 'Pek på den du tror har hatt flest one night stands?'),
    ('ICEBREAKER', 'Pek på den du tror er shavet og klar for alt?'),
    ('ICEBREAKER', 'Pek på den du tror er flinkest til å synge?'),
    ('ICEBREAKER', 'Pek på den du tror onanerer mest?'),
    ('ICEBREAKER', 'Pek på den du tror har runket flest?'),
    ('ICEBREAKER', 'Pek på den du tror har de rareste fetishene?'),
    ('ICEBREAKER', 'Pek på den som har dårligst selvinnsikt?'),
    ('ICEBREAKER', 'Pek på den som blir verst i fylla?'),
    ('ICEBREAKER', 'Hvem er rikest?'),
    ('ICEBREAKER', 'Hvem er mest fink pike/flink gutt?'),
    ('ICEBREAKER', 'Hvem var den forrige Quiz masteren hadde sex med?'),
    ('ICEBREAKER', 'Hvem er den dummeste?'),
    ('ICEBREAKER', 'Hvor mange har den 3. til venstre for QuizMaster hatt sex med?'),
    ('ICEBREAKER', 'Hvor mye har QuizMaster drukket i dag?'),
    ('ICEBREAKER', 'Hvem var den største taperen som barn?'),
    ('ICEBREAKER', 'Hvem var den mest populære på barneskolen?'),
    ('ICEBREAKER', 'Hvem er mest uheldig med dagens outfit?'),
    ('ICEBREAKER', 'Hvem blir mest fjortisfull?'),
    ('ICEBREAKER', 'Har hull i ørene?'),
    ('ICEBREAKER', 'Har pult over 5 stk?'),
    ('ICEBREAKER', 'Eier en bunad?'),
    ('ICEBREAKER', 'Har mørkt hår?'),
    ('ICEBREAKER', 'Er blond?'),
    ('ICEBREAKER', 'Har en fetish?');


INSERT INTO "Games"
    ("GameId", "GameStarted", "PublicGame", "IconImage", "NumberOfQuestions", "CreatorId", "Upvotes")
VALUES
    ('100SPM', true, true, 'EDGY', 100, 'Creator', 15);


INSERT INTO "Questions"
    ("GameId", "QuestionStr")
VALUES
    ('100SPM', 'Hvem er morsomst?'),
    ('100SPM', 'Hvem tror selv den er morsomst?'),
    ('100SPM', 'Hvem har størst kjendisfaktor?'),
    ('100SPM', 'Hvem er best i senga?'),
    ('100SPM', 'Hvem har hatt sex med flest yngre?'),
    ('100SPM', 'Hvem spruter mest massive cumshotten?'),
    ('100SPM', 'Hvem er mest opptatt av utseende?'),
    ('100SPM', 'Hvem er mest fornøyd med eget utseende?'),
    ('100SPM', 'Hvem kommer raskest?'),
    ('100SPM', 'Hvem har størst penis eller er tøffest i trynet?'),
    ('100SPM', 'Hvem har finest smil?'),
    ('100SPM', 'Hvem er mest overlegen?'),
    ('100SPM', 'Hvem er mest sporty?'),
    ('100SPM', 'Hvem har hatt sex med flest?'),
    ('100SPM', 'Hvem har hatt flest orgasmer?'),
    ('100SPM', 'Hvem er mest vill?'),
    ('100SPM', 'Hvem har best kropp?'),
    ('100SPM', 'Hvem er mest spontan?'),
    ('100SPM', 'Hvem er mest uskyldig?'),
    ('100SPM', 'Hvem lager de sykeste lydene i sengen?'),
    ('100SPM', 'Hvem har størst lommebok?'),
    ('100SPM', 'Hvem har finest antrekk?'),
    ('100SPM', 'Hvem har finest legger?'),
    ('100SPM', 'Hvem har finest rumpe?'),
    ('100SPM', 'Hvem har finest frisyre?'),
    ('100SPM', 'Hvem har de vakreste øynene?'),
    ('100SPM', 'Hvem er mest breiskuldret?'),
    ('100SPM', 'Hvem har de mest spennende brystene?'),
    ('100SPM', 'Hvem er festens høyeste?'),
    ('100SPM', 'Hvem har du et lite øye til?'),
    ('100SPM', 'Hvem slipper de verste fisene?'),
    ('100SPM', 'Hvem får du vakrest barn sammen med?'),
    ('100SPM', 'Hvem er mest skoleflink?'),
    ('100SPM', 'Hvem har shavet og er forberedt på alt?'),
    ('100SPM', 'Hvem har lengst tånegler?'),
    ('100SPM', 'Hvem er den største fylliken?'),
    ('100SPM', 'Hvem er den beste til å kysse?'),
    ('100SPM', 'Hvem gir best strippeshow?'),
    ('100SPM', 'Hvem har spenstig latter?'),
    ('100SPM', 'Hvem har lyst å komme i buksa på i kveld?'),
    ('100SPM', 'Hvem blir raskest sjalu?'),
    ('100SPM', 'Hvem tar flest selfies?'),
    ('100SPM', 'Hvem har hatt sex med flest eldre?'),
    ('100SPM', 'Hvem har hatt trekant?'),
    ('100SPM', 'Hvem liker å bruke buttplug?'),
    ('100SPM', 'Hvem har best musikksmak?'),
    ('100SPM', 'Hvem har hatt sex med flest nasjonaliteter?'),
    ('100SPM', 'Hvem synger finest?'),
    ('100SPM', 'Hvem synger jævligst?'),
    ('100SPM', 'Hvem snuser mest?'),
    ('100SPM', 'Hvem tar med seg noen hjem i kveld?'),
    ('100SPM', 'Hvem får kjæreste i år?'),
    ('100SPM', 'Hvem blir gravid først?'),
    ('100SPM', 'Hvem spyr i kveld?'),
    ('100SPM', 'Hvem slutter på studiet?'),
    ('100SPM', 'Hvem blir mest dritafull i kveld?'),
    ('100SPM', 'Hvem blir pappa først?'),
    ('100SPM', 'Hvem gifter seg først?'),
    ('100SPM', 'Hvem har finest lepper?'),
    ('100SPM', 'Hvem har størst fot?'),
    ('100SPM', 'Hvem er mest klar for arbeidslivet?'),
    ('100SPM', 'Hvem kler briller best?'),
    ('100SPM', 'Hvem skiller seg mest ut i mengden?'),
    ('100SPM', 'Hvem ligner mest på ei høne?'),
    ('100SPM', 'Hvem rir best?'),
    ('100SPM', 'Hvem stikker mest?'),
    ('100SPM', 'Hvem lukter best?'),
    ('100SPM', 'Hvem lyser opp rommet?'),
    ('100SPM', 'Hvem runker mest?'),
    ('100SPM', 'Hvem tar seg mest på brystene?'),
    ('100SPM', 'Hvem ser mest på porno?'),
    ('100SPM', 'Hvem fingrer mest?'),
    ('100SPM', 'Hvem drikker raskest?'),
    ('100SPM', 'Hvem googler seg selv oftest?'),
    ('100SPM', 'Hvem gir mest til veldedighet?'),
    ('100SPM', 'Hvem spiller et instrument best?'),
    ('100SPM', 'Hvem er en svett gamer?'),
    ('100SPM', 'Hvem er mest fotogen?'),
    ('100SPM', 'Hvem har blitt pumpet?'),
    ('100SPM', 'Hvem er den verste sjåføren?'),
    ('100SPM', 'Hvem er mest religiøs?'),
    ('100SPM', 'Hvem har hatt sex i telt?'),
    ('100SPM', 'Hvem ville du vært på en øde øy med?'),
    ('100SPM', 'Hvem har flest filmer på telefonen sin?'),
    ('100SPM', 'Hvem bruker fake-ID?'),
    ('100SPM', 'Hvem har hatt sex utendørs?'),
    ('100SPM', 'Hvem er oftest forsinket?'),
    ('100SPM', 'Hvem har kortest telefonsamtaler?'),
    ('100SPM', 'Hvem er mest ubesluttsom?'),
    ('100SPM', 'Hvem tror på synske?'),
    ('100SPM', 'Hvem er minst flink å bruke prevensjon?'),
    ('100SPM', 'Hvem ser på The Kardashians?'),
    ('100SPM', 'Hvem er mest bortskjemt?'),
    ('100SPM', 'Hvem jukser mest?'),
    ('100SPM', 'Hvem har hatt kjønnssykdommer?'),
    ('100SPM', 'Hvem har mest humørsvingninger?'),
    ('100SPM', 'Hvem har størst baller?'),
    ('100SPM', 'Hvem kunne spist mest sushi?'),
    ('100SPM', 'Hvem er lengst i dusjen?'),
    ('100SPM', 'Hvem skal ta bonski sammen med deg?');


INSERT INTO "Games"
    ("GameId", "GameStarted", "PublicGame", "IconImage", "NumberOfQuestions", "CreatorId", "Upvotes")
VALUES
    ('DIRTY', true, true, 'DIRTY', 100, 'Creator', 14);


INSERT INTO "Questions"
    ("GameId", "QuestionStr")
VALUES
    ('DIRTY', 'Hvem lager de morsomste vorsene?'),
    ('DIRTY', 'Hvem bruker mest penger på byen?'),
    ('DIRTY', 'Hvem har finest kjønnsorgan?'),
    ('DIRTY', 'Hvem er mest harry?'),
    ('DIRTY', 'Hvem er mest dirty?'),
    ('DIRTY', 'Hvem har mest sexy antrekk?'),
    ('DIRTY', 'Hvem gir snusboksen videre med et kyss?'),
    ('DIRTY', 'Hvem er alltid med på fylla?'),
    ('DIRTY', 'Hvem kjører mest brannbil?'),
    ('DIRTY', 'Hvem er mest luremus?'),
    ('DIRTY', 'Hvem mistet jomfrudommen først?'),
    ('DIRTY', 'Hvem mistet jomfrudommen sist?'),
    ('DIRTY', 'Hvem har flest sexleketøy?'),
    ('DIRTY', 'Hvem kunne kjøpt sex?'),
    ('DIRTY', 'Hvem har sykeste fetishen?'),
    ('DIRTY', 'Hvem gir best rimjob?'),
    ('DIRTY', 'Hvem sender flest nudes?'),
    ('DIRTY', 'Hvem mottar flest nudes?'),
    ('DIRTY', 'Hvem har en dilf/milf?'),
    ('DIRTY', 'Hvem har sexet flest fra Tinder?'),
    ('DIRTY', 'Hvem svelger alltid?'),
    ('DIRTY', 'Hvem kommer flest ganger i løpet av en økt?'),
    ('DIRTY', 'Hvem har flest ONS?'),
    ('DIRTY', 'Hvem har sugd en hund for 100.000 kr?'),
    ('DIRTY', 'Hvem blir ferdig på 2 minutter?'),
    ('DIRTY', 'Hvem svetter mest under sex?'),
    ('DIRTY', 'Hvem har hatt sex med flest?'),
    ('DIRTY', 'Hvem er festens sugeguri?'),
    ('DIRTY', 'Hvem er festens slikkerolf?'),
    ('DIRTY', 'Hvem vil du komme i buksa på i kveld?'),
    ('DIRTY', 'Hvem sovner under sex?'),
    ('DIRTY', 'Hvem liker BDSM?'),
    ('DIRTY', 'Hvem er mest kreativ i senga?'),
    ('DIRTY', 'Hvem jobber mest på byen?'),
    ('DIRTY', 'Hvem i rommet er best i senga?'),
    ('DIRTY', 'Hvem får mest oppmerksomhet på byen?'),
    ('DIRTY', 'Hvem får oftest whiskydick?'),
    ('DIRTY', 'Hvem blir mest ulik seg selv på fylla?'),
    ('DIRTY', 'Hvem chugger raskest?'),
    ('DIRTY', 'Hvem blir mest rejecta på byen?'),
    ('DIRTY', 'Hvem shotter mest?'),
    ('DIRTY', 'Hvem er beste wingman/woman?'),
    ('DIRTY', 'Hvem tar av mest på vors?'),
    ('DIRTY', 'Hvem har størst busk?'),
    ('DIRTY', 'Hvem er vorsets kamasutra?'),
    ('DIRTY', 'Hvem har onanert før vors?'),
    ('DIRTY', 'Hvem har sugd den mest massive black anacondaen?'),
    ('DIRTY', 'Hvem er kåteste i rommet?'),
    ('DIRTY', 'Hvem kunne meldt seg på Ex on the Beach?'),
    ('DIRTY', 'Hvem er lettest på tråden?'),
    ('DIRTY', 'Hvem deler sexlivet sitt med alle?'),
    ('DIRTY', 'Hvem faker flest orgasmer?'),
    ('DIRTY', 'Hvem er høylytt i sengen?'),
    ('DIRTY', 'Hvem får oftest fylleangst?'),
    ('DIRTY', 'Hvem er den største goldgraveren?'),
    ('DIRTY', 'Hvem er den største cougaren?'),
    ('DIRTY', 'Hvem ville sexet faren/moren til en venn?'),
    ('DIRTY', 'Hvem kunne solgt brukte truser på nett?'),
    ('DIRTY', 'Hvem shopper flest angrepiller?'),
    ('DIRTY', 'Hvem er oftest å se på helsestasjonen?'),
    ('DIRTY', 'Hvem loker mest rundt på Pornhub?'),
    ('DIRTY', 'Hvem bruker buttpluggen flittigst?'),
    ('DIRTY', 'Hvem er minst kresen?'),
    ('DIRTY', 'Hvem ble utestengt under en trekant?'),
    ('DIRTY', 'Hvem er mest egoistisk i sengen?'),
    ('DIRTY', 'Hvem hopper rett inn i tørt føre?'),
    ('DIRTY', 'Hvem filmer seg selv under sex?'),
    ('DIRTY', 'Hvem har hatt flest FF?'),
    ('DIRTY', 'Hvem er festens Dora the Explorer?'),
    ('DIRTY', 'Hvem har ligget med en kjendis kun fordi han/hun er kjent?'),
    ('DIRTY', 'Hvem er vorsets Mr. Worldwide?'),
    ('DIRTY', 'Hvem fikk du best førsteinntrykk av?'),
    ('DIRTY', 'Hvem tåler minst alkohol?'),
    ('DIRTY', 'Hvem kunne tatovert kjærestens navn?'),
    ('DIRTY', 'Hvem byr mest opp til dans?'),
    ('DIRTY', 'Hvem gir best strippeshow?'),
    ('DIRTY', 'Hvem deler minst av sexlivet sitt?'),
    ('DIRTY', 'Hvem liker å bli choket?'),
    ('DIRTY', 'Hvem har hatt sex med flere enn en person på en kveld?'),
    ('DIRTY', 'Hvem er mest kry av eget utstyr?'),
    ('DIRTY', 'Hvem er usynlig i sengen?'),
    ('DIRTY', 'Hvem sier mest nei til sex?'),
    ('DIRTY', 'Hvem har finest nippler?'),
    ('DIRTY', 'Hvem blir pappa først?'),
    ('DIRTY', 'Hvem hadde du hatt det morsomst på ferie med?'),
    ('DIRTY', 'Hvem lyser opp rommet?'),
    ('DIRTY', 'Hvem er mest omtenksom?'),
    ('DIRTY', 'Hvem er mest sjarmerende?'),
    ('DIRTY', 'Hvem har finest smil?'),
    ('DIRTY', 'Hvem liker å bli kalt daddy?'),
    ('DIRTY', 'Hvem squirter mest?'),
    ('DIRTY', 'Hvem har hatt sex med flere enn 20?'),
    ('DIRTY', 'Hvem er mest fan av analsex?'),
    ('DIRTY', 'Hvem kunne tatt en Northug?'),
    ('DIRTY', 'Hvem kunne flashet for en gratis taxitur?'),
    ('DIRTY', 'Hvem lager de sykeste lydene i sengen?'),
    ('DIRTY', 'Hvem puler til musikk?'),
    ('DIRTY', 'Hvem kunne stjålet en venninnes tidligere sexpartner?'),
    ('DIRTY', 'Hvem kunne hatt sex i foreldrenes seng?'),
    ('DIRTY', 'Hvem skal velge tre stk å chugge resten av drikken med?');


INSERT INTO "Games"
    ("GameId", "GameStarted", "PublicGame", "IconImage", "NumberOfQuestions", "CreatorId", "Upvotes")
VALUES
    ('PEKELEKEN', true, true, 'DIRTY', 100, 'Creator', 17);


INSERT INTO "Questions"
    ("GameId", "QuestionStr")
VALUES
    ('PEKELEKEN', 'Hvem tenker mest koffert?'),
    ('PEKELEKEN', 'Hvem tror selv de er morsomst?'),
    ('PEKELEKEN', 'Hvem har størst kjendisfaktor innen pornobransjen?'),
    ('PEKELEKEN', 'Hvem er best i senga?'),
    ('PEKELEKEN', 'Hvem har hatt sex med flest fra 99-kullet?'),
    ('PEKELEKEN', 'Hvem har sprutet den mest massive cumshotten?'),
    ('PEKELEKEN', 'Hvem er mest opptatt av utseende på jenta?'),
    ('PEKELEKEN', 'Hvem er mest fornøyd med eget utseende?'),
    ('PEKELEKEN', 'Hvem kommer raskest?'),
    ('PEKELEKEN', 'Hvem har størst penis?'),
    ('PEKELEKEN', 'Hvem er mest opptatt av størrelsen på leppene?'),
    ('PEKELEKEN', 'Hvem tror selv de er best i senga?'),
    ('PEKELEKEN', 'Hvem er mest sporty?'),
    ('PEKELEKEN', 'Hvem har hatt sex med flest?'),
    ('PEKELEKEN', 'Hvem har hatt flest orgasmer?'),
    ('PEKELEKEN', 'Hvem er mest vill?'),
    ('PEKELEKEN', 'Hvem har best kropp?'),
    ('PEKELEKEN', 'Hvem er mest opptatt av størrelse?'),
    ('PEKELEKEN', 'Hvem er mest uskyldig?'),
    ('PEKELEKEN', 'Hvem lager de sykeste lydene i senga?'),
    ('PEKELEKEN', 'Hvem har hatt den lengste økta?'),
    ('PEKELEKEN', 'Hvem har på det mest sexy undertøyet?'),
    ('PEKELEKEN', 'Hvem har fineste leggene?'),
    ('PEKELEKEN', 'Hvem har fineste rumpe?'),
    ('PEKELEKEN', 'Hvem er finest stelt der nedentil?'),
    ('PEKELEKEN', 'Hvem har de vakreste øynene?'),
    ('PEKELEKEN', 'Hvem er mest breiskuldret?'),
    ('PEKELEKEN', 'Hvem har de mest spennende brystene?'),
    ('PEKELEKEN', 'Hvem er festens høyeste?'),
    ('PEKELEKEN', 'Hvem har du et lite øye til?'),
    ('PEKELEKEN', 'Hvem slipper de verste fisene?'),
    ('PEKELEKEN', 'Hvem får du vakrest barn sammen med?'),
    ('PEKELEKEN', 'Hvem er mest skoleflink?'),
    ('PEKELEKEN', 'Hvem har shavet og er forberedt på alt?'),
    ('PEKELEKEN', 'Hvem har lengst tånegler?'),
    ('PEKELEKEN', 'Hvem er den største fylliken?'),
    ('PEKELEKEN', 'Hvem er den beste til å kysse?'),
    ('PEKELEKEN', 'Hvem gir best strippeshow?'),
    ('PEKELEKEN', 'Hvem har spenstig latter?'),
    ('PEKELEKEN', 'Hvem har lyst å komme i buksa på noen i kveld?'),
    ('PEKELEKEN', 'Hvem blir raskest sjalu?'),
    ('PEKELEKEN', 'Hvem ligner mest på en taco?'),
    ('PEKELEKEN', 'Hvem har hatt sex med flest eldre?'),
    ('PEKELEKEN', 'Hvem har hatt trekant?'),
    ('PEKELEKEN', 'Hvem liker å bruke buttplug?'),
    ('PEKELEKEN', 'Hvem har breiest rumpehull?'),
    ('PEKELEKEN', 'Hvem har hatt sex med flest nasjonaliteter?'),
    ('PEKELEKEN', 'Hvem har mest porno-inspirert sex?'),
    ('PEKELEKEN', 'Hvem suger jævligst?'),
    ('PEKELEKEN', 'Hvem snuser mest?'),
    ('PEKELEKEN', 'Hvem tar med seg noen hjem i kveld?'),
    ('PEKELEKEN', 'Hvem får kjæreste i år?'),
    ('PEKELEKEN', 'Hvem blir gravid først?'),
    ('PEKELEKEN', 'Hvem spyr i kveld?'),
    ('PEKELEKEN', 'Hvem er den trangeste?'),
    ('PEKELEKEN', 'Hvem blir mest drita i kveld?'),
    ('PEKELEKEN', 'Hvem må holde den til høyre på låret i 30 sekunder på en seksuell måte?'),
    ('PEKELEKEN', 'Hvem gifter seg først?'),
    ('PEKELEKEN', 'Hvem har finest lepper?'),
    ('PEKELEKEN', 'Hvem svelger mest?'),
    ('PEKELEKEN', 'Hvem holder lengst?'),
    ('PEKELEKEN', 'Hvem må holde den til venstre på låret i 1 minutt?'),
    ('PEKELEKEN', 'Hvem skiller seg mest ut i mengden?'),
    ('PEKELEKEN', 'Hvem ligner mest på ei høne?'),
    ('PEKELEKEN', 'Hvem rir best?'),
    ('PEKELEKEN', 'Hvem stikker mest?'),
    ('PEKELEKEN', 'Hvem lager den beste pornofilmen sammen med?'),
    ('PEKELEKEN', 'Hvem lyser opp rommet?'),
    ('PEKELEKEN', 'Hvem runker mest?'),
    ('PEKELEKEN', 'Hvem tar seg mest på puppene?'),
    ('PEKELEKEN', 'Hvem ser mest på porno?'),
    ('PEKELEKEN', 'Hvem fingrer mest?'),
    ('PEKELEKEN', 'Hvem drikker raskest?'),
    ('PEKELEKEN', 'Hvem har mest anal?'),
    ('PEKELEKEN', 'Hvem bruker mest penger på sexleketøy?'),
    ('PEKELEKEN', 'Hvem blåser fløyta best?'),
    ('PEKELEKEN', 'Hvem har drukket mest i kveld?'),
    ('PEKELEKEN', 'Hvem er mest fotogen?'),
    ('PEKELEKEN', 'Hvem har blitt pumpet?'),
    ('PEKELEKEN', 'Hvem er den verste sjåføren?'),
    ('PEKELEKEN', 'Hvem har gjort flest ting som er minst religiøst?'),
    ('PEKELEKEN', 'Hvem har hatt sex i telt?'),
    ('PEKELEKEN', 'Hvem ville du vært på en øde øy med?'),
    ('PEKELEKEN', 'Hvem har flest nakenbilder på telefonen sin?'),
    ('PEKELEKEN', 'Hvem begynte å drikke først?'),
    ('PEKELEKEN', 'Hvem har hatt sex utendørs?'),
    ('PEKELEKEN', 'Hvem bruker lengst tid på å komme?'),
    ('PEKELEKEN', 'Hvem har kortest penis?'),
    ('PEKELEKEN', 'Hvem er minst tiltrukket av?'),
    ('PEKELEKEN', 'Hvem er mest sannsynlig til å ha sex i det offentlige?'),
    ('PEKELEKEN', 'Hvem er minst flink å bruke prevensjon?'),
    ('PEKELEKEN', 'Hvem har spennende ting i nattbordsskuffen?'),
    ('PEKELEKEN', 'Hvem er mest bortskjemt?'),
    ('PEKELEKEN', 'Hvem jukser mest?'),
    ('PEKELEKEN', 'Hvem har hatt kjønnssykdommer?'),
    ('PEKELEKEN', 'Hvem kunne ha hatt sex med flest på en uke?'),
    ('PEKELEKEN', 'Hvem har størst baller?'),
    ('PEKELEKEN', 'Hvem kunne svelget mest cum?'),
    ('PEKELEKEN', 'Hvem koser med seg selv i dusjen?'),
    ('PEKELEKEN', 'Hvem skal ta bonski sammen med deg?');


INSERT INTO "Games"
    ("GameId", "GameStarted", "PublicGame", "IconImage", "NumberOfQuestions", "CreatorId", "Upvotes")
VALUES
    ('FYLLA', true, true, 'DIRTY', 84, 'Creator', 12);


INSERT INTO "Questions"
    ("GameId", "QuestionStr")
VALUES
    ('FYLLA', 'Hvem la du først merke til da du kom på dette vorset?'),
    ('FYLLA', 'Hvem hadde ditcha gjengen for et ligg?'),
    ('FYLLA', 'Hvem har en eks som kunne dratt dem med på Ex on the Beach?'),
    ('FYLLA', 'Hvem her har en drøm om å bli TikTok-kjendis?'),
    ('FYLLA', 'Hvem i rommet har den mørkeste humoren?'),
    ('FYLLA', 'Hvem er på den lengste tørkeperioden?'),
    ('FYLLA', 'Hvem her ville du hatt til å gjøre en klein tjeneste?'),
    ('FYLLA', 'Hvem ser litt for bra ut?'),
    ('FYLLA', 'Hvem har skulka flest forelesninger under korona?'),
    ('FYLLA', 'Hvem kunne ligget med noen bare fordi vedkommende er en kjendis?'),
    ('FYLLA', 'Hvem liker å bli kvelt?'),
    ('FYLLA', 'Hvem kunne ha hatt sex mens alle i rommet så på?'),
    ('FYLLA', 'Hvem her kunne tjent seg rik på aksjer?'),
    ('FYLLA', 'Hvem klarer ikke å holde kjeft på kino?'),
    ('FYLLA', 'Hvem drar tidligst hjem fra byen?'),
    ('FYLLA', 'Hvem kunne lett brukt 500 kr på McDonalds?'),
    ('FYLLA', 'Hvem elsker nach?'),
    ('FYLLA', 'Hvem har best draget på byen?'),
    ('FYLLA', 'Personen til venstre for deg er på utkikk etter en date, og du er wingman. Hvem er den heldige utvalgte?'),
    ('FYLLA', 'Hvem her er mest mystisk?'),
    ('FYLLA', 'Hvem her har en hemmelig OnlyFans?'),
    ('FYLLA', 'Hvem her betaler for OnlyFans?'),
    ('FYLLA', 'Hvem deler alltid litt for mye? (TMI)'),
    ('FYLLA', 'Hvem tør du egentlig ikke å kaste til?'),
    ('FYLLA', 'Hvem skal bytte plass med deg?'),
    ('FYLLA', 'Hvem i rommet kunne klart å flørte seg unna en bot?'),
    ('FYLLA', 'Hvem her kunne du byttet liv med?'),
    ('FYLLA', 'Hvem ville du helst vært grøtbror/stangsøster med?'),
    ('FYLLA', 'Du skal på ferie i 1 uke og må ha med deg et reisefølge. Du kan ikke velge noen av de du kom på dette vorset med. Hvem tar du med?'),
    ('FYLLA', 'Hvem i rommet bruker mest penger på Pepsi Max?'),
    ('FYLLA', 'Hvem burde drikke mer?'),
    ('FYLLA', 'Hvem her kunne ligget med sjefen sin?'),
    ('FYLLA', 'Hvem sløser mest penger?'),
    ('FYLLA', 'Hvem har på finest undertøy?'),
    ('FYLLA', 'Året er 2050, hvem ser best ut?'),
    ('FYLLA', 'Hvem her er mest ulik deg selv?'),
    ('FYLLA', 'Hvem hadde passet best inn på Paradise Hotel?'),
    ('FYLLA', 'Hvem her kunne våknet opp i et annet land etter en kveld på fylla?'),
    ('FYLLA', 'Du er invitert i bryllupet til søsteren din i august, men mangler en "plus one". Hvem her tar du med deg i håp om å sjarmere familien?'),
    ('FYLLA', 'Hvem er hardest på flaska?'),
    ('FYLLA', 'Hvem er dårligst på å ta imot komplimenter?'),
    ('FYLLA', 'Hvem bidrar mest til å lage god stemning?'),
    ('FYLLA', 'Hvem kunne du tenkt deg å bli bedre kjent med?'),
    ('FYLLA', 'Hvem er flinkest til å huske navn?'),
    ('FYLLA', 'Hvem er mest spandabel?'),
    ('FYLLA', 'Hvem har det mest i kjeften?'),
    ('FYLLA', 'Hvem ser du plutselig i en video på Pornhub?'),
    ('FYLLA', 'Hvem har finest nese?'),
    ('FYLLA', 'Du og den til høyre for deg skal ha en trekant, hvem er den siste personen som blir med?'),
    ('FYLLA', 'Hvem her må ta seg et glass vann?'),
    ('FYLLA', 'Hvem drikker alltid litt for mye?'),
    ('FYLLA', 'Hvem er mest fjern og har ikke fått med seg en dritt av leken så langt?'),
    ('FYLLA', 'Hvem har oftest fylleangst?'),
    ('FYLLA', 'Hvem er hyggeligere enn de ser ut som?'),
    ('FYLLA', 'Hvem her har ikke sett Friends?'),
    ('FYLLA', 'Hvem har mest skjermtid på mobilen?'),
    ('FYLLA', 'Hvem er mest gjerrig?'),
    ('FYLLA', 'Hvem er flinkest til å gi komplimenter?'),
    ('FYLLA', 'Hvem bruker mest på treningssenteret?'),
    ('FYLLA', 'Hvem har de største ølbrillene?'),
    ('FYLLA', 'Hvem her har mest tro på trendy dietter?'),
    ('FYLLA', 'Hvem tror du den til høyre for deg kunne dratt på date med?'),
    ('FYLLA', 'Hvem ghoster flest?'),
    ('FYLLA', 'Hvem bryr seg mest om å fremstå bra på sosiale medier?'),
    ('FYLLA', 'Hvem bare har det?'),
    ('FYLLA', 'Hvem sender mest nudes?'),
    ('FYLLA', 'Hvem sin telefon ville du snoket i?'),
    ('FYLLA', 'Hvem hadde den siste positive klamydia-testen?'),
    ('FYLLA', 'Hvem blir fortest betatt?'),
    ('FYLLA', 'Hvem har den største hangoveren imorgen?'),
    ('FYLLA', 'Hvem ser freshest ut idag?'),
    ('FYLLA', 'Hvem har størst sannsynlighet for å bli svindlet?'),
    ('FYLLA', 'Hvem liker dirtytalk?'),
    ('FYLLA', 'Hvem er mest kravstor?'),
    ('FYLLA', 'Hvem er den morsomste?'),
    ('FYLLA', 'Hvem er mest catfish?'),
    ('FYLLA', 'Hvem er den største flørtepusen?'),
    ('FYLLA', 'Hvem er mest konfliktsky?'),
    ('FYLLA', 'Hvem er minst konfliktsky?'),
    ('FYLLA', 'Hvem tror på alt de leser?'),
    ('FYLLA', 'Hvem ville du dratt på fest med igjen?'),
    ('FYLLA', 'Hvem kunne ligget med en som er over 20 år eldre enn dem selv?'),
    ('FYLLA', 'Hvem her har hatt den største glow-upen siden ungdomsskolen?'),
    ('FYLLA', 'Hvem har du fått et best inntrykk av i løpet av spillet?'),
    ('FYLLA', 'Hvem fylletekster eksen sin?');
